prevent error which occures in php 8.2
keycdn/cdn-enabler pull request #50
Opened 2023-09-13 06:01 UTC by cpalexh

2023-09-18 06:24 UTC, tfgrass approved these changes

2023-10-12 10:12 UTC, svenba requested changes

2023-10-12 10:12 UTC, svenba commented on inc/cdn_enabler_engine.class.php
> +        ob_start( [static::class, 'end_buffering'] );
Why not using self::class instead of static::class?

2023-10-13 07:54 UTC, svenba approved these changes

2023-10-13 07:54 UTC, merged